/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__layout';
import { Route as MainImport } from './routes/main';
import { Route as AboutImport } from './routes/about';

// Create/Update Routes

const MainRoute = MainImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRoute,
} as any);

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof AboutImport;
      parentRoute: typeof rootRoute;
    };
    '/main': {
      id: '/main';
      path: '/main';
      fullPath: '/main';
      preLoaderRoute: typeof MainImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute;
  '/main': typeof MainRoute;
}

export interface FileRoutesByTo {
  '/about': typeof AboutRoute;
  '/main': typeof MainRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/about': typeof AboutRoute;
  '/main': typeof MainRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/about' | '/main';
  fileRoutesByTo: FileRoutesByTo;
  to: '/about' | '/main';
  id: '__root__' | '/about' | '/main';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute;
  MainRoute: typeof MainRoute;
}

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  MainRoute: MainRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/about",
        "/main"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/main": {
      "filePath": "main.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
